"""Controlled values for explicit OAS-K recovery workflows."""

from __future__ import annotations

from enum import StrEnum


class BackupReason(StrEnum):
    MANUAL = "MANUAL"
    BEFORE_RESTORE = "BEFORE_RESTORE"
    BEFORE_IMPORT = "BEFORE_IMPORT"
    BEFORE_RESET = "BEFORE_RESET"
    BEFORE_RELOCATION = "BEFORE_RELOCATION"
    BEFORE_UPGRADE = "BEFORE_UPGRADE"


class RecoveryStatus(StrEnum):
    HEALTHY = "HEALTHY"
    DATABASE_MISSING = "DATABASE_MISSING"
    DATABASE_INVALID = "DATABASE_INVALID"
    SCHEMA_INCOMPATIBLE = "SCHEMA_INCOMPATIBLE"
    REGISTRY_POINTER_INVALID = "REGISTRY_POINTER_INVALID"
    DATA_ROOT_UNAVAILABLE = "DATA_ROOT_UNAVAILABLE"
    BACKUP_AVAILABLE = "BACKUP_AVAILABLE"
    NO_BACKUP_AVAILABLE = "NO_BACKUP_AVAILABLE"


class RecoveryAction(StrEnum):
    RESTORE_LAST_BACKUP = "RESTORE_LAST_BACKUP"
    SELECT_BACKUP = "SELECT_BACKUP"
    IMPORT_EXISTING_DATABASE = "IMPORT_EXISTING_DATABASE"
    RESET_TO_DEFAULT = "RESET_TO_DEFAULT"
    SELECT_DATA_ROOT = "SELECT_DATA_ROOT"
    OPEN_DIAGNOSTICS = "OPEN_DIAGNOSTICS"
    CANCEL = "CANCEL"


APPLICATION_DATA_FORMAT_VERSION = 1
DATABASE_ARCHIVE_PATH = "database/OAS-K.db"
MANIFEST_ARCHIVE_PATH = "manifest.json"
RECOVERY_STAGING_DIRECTORY = "recovery_staging"
BACKUP_DATABASE_DIRECTORY = "database"
BACKUP_APPLICATION_DATA_DIRECTORY = "application_data"
